# Generated by Django 3.2.9 on 2022-01-19 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 19, 5, 54, 48, 759583)),
        ),
        migrations.AlterField(
            model_name='newnotifications',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 19, 5, 54, 48, 758584)),
        ),
        migrations.AlterField(
            model_name='oldnotifications',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 5, 54, 48, 757563)),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 1, 19, 5, 54, 48, 763580)),
        ),
    ]
