# Generated by Django 3.2.9 on 2022-01-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220119_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='_User',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ToDoList',
        ),
        migrations.RemoveField(
            model_name='message',
            name='User',
        ),
        migrations.RemoveField(
            model_name='newnotifications',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oldnotifications',
            name='user',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='User',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='NewNotifications',
        ),
        migrations.DeleteModel(
            name='OldNotifications',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
