# Generated by Django 3.2.9 on 2022-01-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220120_0420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
